---
# Oğuzhan Dilber
# 07.07.2021


- name: RSYSLOG
  hosts: rsyslog
  become: yes
  remote_user: oguzhan
  roles:
    - role: rsyslog
  tags: rsyslog

- name: NETSTAT
  hosts: netstat
  become: yes
  remote_user: oguzhan
  roles:
    - role: netstat       
  tags: netstat   

- name: DockerVersion
  hosts: docker-version
  become: yes
  remote_user: oguzhan
  roles:
    - role: docker
  tags: docker 

- name: KubectlVersion
  hosts: kubectl-version
  become: yes
  remote_user: oguzhan
  roles:
    - role: kubectl
  tags: kubectl 

- name: TcpDump
  hosts: tcpdump
  become: yes
  remote_user: oguzhan
  roles: 
    - role: tcpdump
  tags: tcpdump  
